#!/usr/bin/python

from subprocess import Popen,PIPE

p1=Popen(["free", "-m", "-h", "-t"], stdout=PIPE)
freeout, error=p1.communicate()

print "The memory distribution is as follows:"

print "================================"

print freeout 

print "================================="
